# Generated by Selenium IDE
import pytest
import time
import json
from app import app, db
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPcwikitests():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    db.init_app(app)
    db.create_all()

    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
    db.drop_all()

  
  def test_logintest(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.CSS_SELECTOR, "#signup-form #floatingInput").click()
    self.driver.find_element(By.CSS_SELECTOR, "#signup-form #floatingInput").send_keys("potat")
    self.driver.find_element(By.ID, "signupPass1").click()
    self.driver.find_element(By.ID, "signupPass1").send_keys("yes")
    self.driver.find_element(By.ID, "signupPass2").click()
    self.driver.find_element(By.ID, "signupPass2").send_keys("yes")
    self.driver.find_element(By.ID, "signUpButton").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "floatingInput").click()
    self.driver.find_element(By.ID, "floatingInput").send_keys("potat")
    self.driver.find_element(By.ID, "floatingPassword").click()
    self.driver.find_element(By.ID, "floatingPassword").send_keys("yes")
    self.driver.find_element(By.NAME, "Remember Me").click()
    self.driver.find_element(By.NAME, "Sign In").click()
    self.driver.find_element(By.LINK_TEXT, "Learn").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.CSS_SELECTOR, "#signup-form #floatingInput").click()
    self.driver.find_element(By.CSS_SELECTOR, "#signup-form #floatingInput").send_keys("potat")
    self.driver.find_element(By.ID, "signupPass1").click()
    self.driver.find_element(By.ID, "signupPass1").send_keys("yes")
    self.driver.find_element(By.ID, "signupPass2").click()
    self.driver.find_element(By.ID, "signupPass2").send_keys("yes")
    self.driver.find_element(By.ID, "signUpButton").click()
  
  def test_quizTest(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.CSS_SELECTOR, "#signup-form #floatingInput").click()
    self.driver.find_element(By.CSS_SELECTOR, "#signup-form #floatingInput").send_keys("yes")
    self.driver.find_element(By.ID, "signupPass1").click()
    self.driver.find_element(By.ID, "signupPass1").send_keys("yes")
    self.driver.find_element(By.ID, "signupPass2").click()
    self.driver.find_element(By.ID, "signupPass2").send_keys("yes")
    self.driver.find_element(By.ID, "signUpButton").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-3").click()
    self.driver.find_element(By.LINK_TEXT, "Quiz").click()
    self.driver.find_element(By.ID, "question_1-0").click()
    self.driver.find_element(By.ID, "question_2-1").click()
    self.driver.find_element(By.ID, "question_3-2").click()
    self.driver.find_element(By.ID, "question_4-3").click()
    self.driver.find_element(By.ID, "question_5-0").click()
    self.driver.find_element(By.ID, "question_6-0").click()
    self.driver.find_element(By.NAME, "question_7").click()
    self.driver.find_element(By.NAME, "question_7").send_keys("7")
    self.driver.find_element(By.ID, "quiz-submission").click()
    self.driver.find_element(By.CSS_SELECTOR, ".accordion-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".accordion-button").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
